// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaULPI4Vuf32JCz3TdVtxiTukAjToqaR0',
    appId: '1:697428719622:web:c19ca6feee7673e319ab87',
    messagingSenderId: '697428719622',
    projectId: 'flutterflow-test-4a83e',
    authDomain: 'flutterflow-test-4a83e.firebaseapp.com',
    storageBucket: 'flutterflow-test-4a83e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeSWWTJQTral9oT3QUFXKon-VuBo3BzE4',
    appId: '1:697428719622:android:e8ff6cc4b65be41119ab87',
    messagingSenderId: '697428719622',
    projectId: 'flutterflow-test-4a83e',
    storageBucket: 'flutterflow-test-4a83e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJTiHJn1NUhX5jBzQKkXE-xscpPRSiM5k',
    appId: '1:697428719622:ios:f1f9b1f60f0e1d1519ab87',
    messagingSenderId: '697428719622',
    projectId: 'flutterflow-test-4a83e',
    storageBucket: 'flutterflow-test-4a83e.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJTiHJn1NUhX5jBzQKkXE-xscpPRSiM5k',
    appId: '1:697428719622:ios:735a95c6920665b419ab87',
    messagingSenderId: '697428719622',
    projectId: 'flutterflow-test-4a83e',
    storageBucket: 'flutterflow-test-4a83e.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
